experiment_name: deeplabv3plus_resnet34_cbam

model:
  architecture: deeplabv3plus
  encoder: resnet34
  encoder_weights: imagenet
  num_classes: 4

training:
  epochs: 70
  batch_size: 16
  learning_rate: 0.007
  momentum: 0.9
  weight_decay: 0.0001
  num_workers: 0
  save_every_n_epochs: 5

scheduler:
  type: poly
  power: 0.9

loss:
  use_ce: true
  use_dice: true
  class_weights: [0.2, 5.0, 2.0, 2.5] 

data:
  train_dir: D:/cyclone/dataset/train
  image_size: 512

output:
  checkpoint_dir: D:/cyclone/checkpoints/resnet34_cbam
  log_dir: D:/cyclone/outputs/resnet34_cbam/logs
  result_dir: D:/cyclone/outputs/resnet34_cbam/results
